name: mriseqtype
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.10.11
  - certifi=2021.5.30
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=21.2.2
  - python=3.6.13
  - readline=8.2
  - setuptools=58.0.4
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - charset-normalizer==2.0.12
    - click==8.0.4
    - cycler==0.11.0
    - dataclasses==0.8
    - decorator==4.4.2
    - dicom2nifti==2.4.5
    - docopt==0.6.2
    - enum34==1.1.10
    - idna==3.4
    - imageio==2.15.0
    - imgaug==0.4.0
    - importlib-metadata==4.8.3
    - kiwisolver==1.3.1
    - matplotlib==3.3.4
    - networkx==2.5.1
    - nibabel==3.2.2
    - numpy==1.19.5
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==0.23.0
    - pandas-ml==0.5.0
    - pillow==8.4.0
    - pipreqs==0.4.11
    - pydicom==2.3.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-gdcm==3.0.19
    - pytz==2022.6
    - pywavelets==1.1.1
    - requests==2.27.1
    - scikit-image==0.17.2
    - scipy==1.5.4
    - sh==1.14.3
    - shapely==1.8.5.post1
    - simpleitk==2.1.1.2
    - six==1.16.0
    - tifffile==2020.9.3
    - torch==1.10.1
    - torchvision==0.11.2
    - typing-extensions==4.1.1
    - urllib3==1.26.12
    - yarg==0.1.9
    - zipp==3.6.0
